#!/usr/bin/env python3
"""
inst_gen.py — SoC Instance Map Generator

Generates SoC-level and SubSystem-level .imap files from:
  - A memory map spreadsheet (XLSX)
  - RTL design analysis output (module_parameters.json)
  - IP spec repository paths

Usage:
  python inst_gen.py --memmap soc_memmap.xlsx \
                     --rtl_params module_parameters.json \
                     --spec_repo /path/to/spec-repo \
                     --chip_prefix MCU_X \
                     --output SOC_XYZ_top.imap
"""

import argparse
import json
import os
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Any

def load_memory_map(xlsx_path: str) -> List[Dict[str, str]]:
    """Parse the SoC memory map spreadsheet."""
    try:
        from openpyxl import load_workbook
        wb = load_workbook(xlsx_path)
        ws = wb.active
    except ImportError:
        print("[WARNING] openpyxl not available, using mock memory map")
        return [
            {"ip_name": "FlexCAN", "inst_name": "FlexCAN_core_0",
             "start_addr": "0x40024000", "end_addr": "0x40027FFF",
             "slot_size": "16KB", "addr_space": "PERIPHERAL",
             "rdb_path": "IP_FlexCAN_SPEC/spec_source/regs/FlexCAN_core_regs.rdb",
             "spec_ref": "IP_FlexCAN_SPEC"},
            {"ip_name": "FlexCAN", "inst_name": "FlexCAN_core_1",
             "start_addr": "0x40028000", "end_addr": "0x4002BFFF",
             "slot_size": "16KB", "addr_space": "PERIPHERAL",
             "rdb_path": "IP_FlexCAN_SPEC/spec_source/regs/FlexCAN_core_regs.rdb",
             "spec_ref": "IP_FlexCAN_SPEC"},
        ]

    entries = []
    headers = [cell.value for cell in next(ws.iter_rows(min_row=1, max_row=1))]
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0] is None:
            continue
        entry = {headers[i]: str(row[i]) if row[i] else "" for i in range(len(headers))}
        entries.append(entry)
    return entries


def load_rtl_params(json_path: str) -> Dict:
    """Load module_parameters.json from design analysis."""
    with open(json_path) as f:
        return json.load(f)


def find_rtl_params_for_instance(
    rtl_params: Dict, instance_name: str
) -> Dict[str, Any]:
    """Extract RTL parameters for a specific instance from the design analysis output."""
    found_params = {}
    search_name = instance_name.lower().replace('_', '')
    
    for module_path, module_data in rtl_params.get('modules', {}).items():
        if search_name in module_path.lower().replace('_', ''):
            for pname, pinfo in module_data.get('parameters', {}).items():
                found_params[pname] = pinfo['default']
            break  # Use first match
    return found_params


def generate_imap(
    memmap: List[Dict],
    rtl_params: Dict,
    spec_repo_root: str,
    chip_prefix: str,
    output_path: str
) -> str:
    """Generate the SoC-level .imap file."""
    
    root = ET.Element('instance', {
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        'spec_id': 'SOC_XYZ',
        'chip_prefix': chip_prefix,
        'paramdef_ref': '../params/SOC_XYZ_top.prm',
        'global_paramdef_ref': '../../../global-params/global_params.prm'
    })
    
    # Add header comment
    root.insert(0, ET.Comment(
        f' Auto-generated SoC Instance Map for {chip_prefix}\n'
        f' Generated by inst_gen.py\n'
        f' Source: {len(memmap)} IP instances from memory map'
    ))
    
    for entry in memmap:
        inst_name = entry.get('inst_name', '')
        reg_elem = ET.SubElement(root, 'reg', {
            'instance_name': inst_name,
            'ip_spec': entry.get('spec_ref', '')
        })
        
        ET.SubElement(reg_elem, 'regs_link', {
            'href': f"../../../{entry.get('rdb_path', '')}"
        })
        ET.SubElement(reg_elem, 'base_address').text = entry.get('start_addr', '0x0')
        ET.SubElement(reg_elem, 'slot_size').text = entry.get('slot_size', '4KB')
        ET.SubElement(reg_elem, 'address_space').text = entry.get('addr_space', 'PERIPHERAL')
        
        # Add RTL parameter overrides
        rtl_inst_params = find_rtl_params_for_instance(rtl_params, inst_name)
        if rtl_inst_params:
            comment = ET.Comment(' RTL Parameters from design analysis ')
            reg_elem.append(comment)
            for pname, pvalue in rtl_inst_params.items():
                override = ET.SubElement(reg_elem, 'param_override', {
                    'param_id': pname
                })
                override.text = str(pvalue)
    
    # Write output
    tree = ET.ElementTree(root)
    ET.indent(tree, space='  ')
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    tree.write(output_path, encoding='utf-8', xml_declaration=True)
    
    print(f"[INFO] Generated .imap with {len(memmap)} instances → {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(description='SoC Instance Map Generator')
    parser.add_argument('--memmap', required=True, help='Memory map XLSX file')
    parser.add_argument('--rtl_params', required=True, help='module_parameters.json')
    parser.add_argument('--spec_repo', required=True, help='Spec repo root directory')
    parser.add_argument('--chip_prefix', required=True, help='Chip family prefix')
    parser.add_argument('--output', required=True, help='Output .imap path')
    args = parser.parse_args()
    
    memmap = load_memory_map(args.memmap)
    rtl_params = load_rtl_params(args.rtl_params)
    
    generate_imap(
        memmap=memmap,
        rtl_params=rtl_params,
        spec_repo_root=args.spec_repo,
        chip_prefix=args.chip_prefix,
        output_path=args.output
    )


if __name__ == '__main__':
    main()